name: phone_authentication
description: Phone authentication for Flutter app. Using Bloc, Firestore, Shared Preferences.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  equatable: ^2.0.3
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  flutter_bloc: ^6.1.1
  pinput: ^1.2.0
  mask_text_input_formatter: ^2.0.0
  cloud_firestore: ^2.2.1
  shared_preferences: ^2.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
